name: BridgeRacing
version: 1.1
main: me.dtqdev.bridgeracing.BridgeRacing
author: dtqdev
depend: [FastBuilder, PlaceholderAPI, WorldEdit]
commands:
  duel:
    description: Mở menu thi đấu hoặc quản lý BridgeRacing.
    aliases: [br]
  leave:
    description: Rời khỏi hàng chờ hoặc trận đấu hiện tại.
    aliases: [brleave]